#!/usr/bin/env bash

info() { printf '\033[34m[%-5s] %s\033[0m\n' 'INFO' "$*" >&2; }
error() { printf '\033[31m[%-5s] %s\033[0m\n' 'ERROR' "$*" >&2; }

if [ "$(id -u)" != '0' ]; then
    error 'Installer requires root privileges' >&2
    exit 1
fi

set -eo pipefail

pwd="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
install_dir='/usr/local/libexec/ps1'
info "Installing to '$install_dir'"

mkdir -p "$install_dir" || {
    error "Failed to create directory '$install_dir'"
    exit 1
}

chmod 755 "$install_dir" || {
    error "Failed to set permissions for '$install_dir'"
    exit 1
}

for f in "$pwd"/scripts/*; do
    cp -r "$f" "$install_dir" || {
        error "Failed to copy '${f##*/}' to '$install_dir'"
        exit 1
    }
    chmod 755 "${install_dir}/${f##*/}" || {
        error "Failed to set executable permissions for '${install_dir}/${f##*/}'"
        exit 1
    }
done

rm -f /usr/local/bin/get-ps1
ln -s "${install_dir}/get-ps1" '/usr/local/bin/get-ps1' || {
    error "Failed to link '${install_dir}/get-ps1' to '/usr/local/bin/get-ps1'"
    exit 1
}

target_user="$SUDO_USER"
[ -z "$target_user" ] \
    && target_user="$USER"

is_root='false'
[ "$target_user" = 'root' ] \
    && is_root='true'

home="$(sudo -u "$target_user" bash -c 'echo $HOME')"

info "Cleaning shell runtime configs"
for sh in bash zsh; do
    ! command -v "$sh" &> /dev/null \
        && continue
    sed -i '/<(get-ps1.*)$/d' "${home}/.${sh}rc" || true
    [ "$is_root" = 'false' ] \
        && sed -i '/<(get-ps1.*)$/d' ~/."${sh}rc" || true
done

if command -v zsh &> /dev/null; then
    info 'Zsh found, installing to ~/.zshrc'
    echo 'source <(get-ps1 zsh)' | sudo -u "$target_user" tee -a "$home"/.zshrc 1> /dev/null || {
        error "Failed to set PS1 in '${home}/.zshrc'"
        exit 1
    }
    [ "$is_root" = 'false' ] \
        && echo 'source <(get-ps1 zsh)' >> ~/.zshrc
fi

info 'Installing to .bashrc'
echo 'source <(get-ps1 bash)' | sudo -u "$target_user" tee -a "$home"/.bashrc 1> /dev/null || {
    error "Failed to set PS1 in '${home}/.bashrc'"
    exit 1
}
[ "$is_root" = 'false' ] \
    && echo 'source <(get-ps1 bash)' >> ~/.bashrc

printf '\033[32m[%-5s] %s\033[0m\n' 'OK' 'All done :)'
info 'Install complete'
