#!/usr/bin/env bash

info() { printf '\033[34m[%-5s] %s\033[0m\n' 'INFO' "$*" >&2; }
warn() { printf '\033[33m[%-5s] %s\033[0m\n' 'WARN' "$*" >&2; }
error() { printf '\033[31m[%-5s] %s\033[0m\n' 'ERROR' "$*" >&2; }

if [ "$(id -u)" = 0 ]; then
    error 'Do not run script as root'
    exit 1
fi

set -eo pipefail

pwd="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

#
# Depend Check
#

declare -a required=('nvim' 'cargo' 'npm' 'rg' 'lua' 'luarocks' 'wget')
declare -a missing=()

for cmd in "${required[@]}"; do
    ! command -v "$cmd" &> /dev/null \
        && missing+=("$cmd")
done

[ "${#missing[@]}" -gt 0 ] \
    && warn "You must install the following dependencies before starting Neovim: ${missing[*]}"

#
# Treesitter Cli
#

tree_sitter_cli_installed='true'
if ! command -v tree-sitter &> /dev/null; then
    pkg="tree-sitter-cli"
    if command -v cargo-binstall &> /dev/null; then
        info "Installing crate binary: $pkg"
        cargo binstall -y "$pkg"
    elif command -v npm &> /dev/null; then
        info "Installing NPM package: $pkg"
        npm install -g --prefix "${HOME}/.local" "$pkg"
        [[ "$PATH" != *"${HOME}/.local/bin"* ]] \
            && warn "Update PATH with: '${HOME}/.local/bin'"
    elif command -v cargo &> /dev/null; then
        info "Building/installing crate: $pkg"
        cargo install "$pkg"
    else
        tree_sitter_cli_installed='false'
    fi
fi

[ "$tree_sitter_cli_installed" = 'false' ] \
    && warn "tree-sitter-cli not installed --" \
        "relying on Mason is safe but may cause" \
        "error messages in Neovim during first init"

#
# Install Config
#

install_dir="${XDG_CONFIG_HOME:-"${HOME}/.config"}/nvim"
if [ -e "$install_dir" ]; then
    info "Backing up '$install_dir'"
    mv -T --backup=t "$install_dir" "${install_dir}~"
fi

info "Installing to '$install_dir'"
cp -r "${pwd}/nvim" "$install_dir"

info 'Install complete'
