#!/usr/bin/env bash

info() { printf '\033[34m[%-5s] %s\033[0m\n' 'INFO' "$*" >&2; }
error() { printf '\033[31m[%-5s] %s\033[0m\n' 'ERROR' "$*" >&2; }

if [ "$(id -u)" = 0 ]; then
    error 'Do not run script as root'
    exit 1
fi

set -eo pipefail

pwd="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

install_dir="${XDG_CONFIG_HOME:-"${HOME}/.config"}/nvim"
if [ -e "$install_dir" ]; then
    info "Backing up '$install_dir'"
    mv -T --backup=t "$install_dir" "${install_dir}~"
fi

info "Installing to '$install_dir'"
cp -r "${pwd}/nvim" "$install_dir"

info 'Install complete'
